version: '3.6'
services:
  database:
    image: postgres:latest
    volumes:
      - mc-job:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=mc-job
      - POSTGRES_PASSWORD=mc@staging
      - POSTGRES_DB=mc-job
    container_name: mc-job-db
  mc-job:
    image: mc-job:1.0-SNAPSHOT
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - TZ=Asia/Tehran
      - 'spring.profiles.active=dev'
      - 'spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/mc-job'
    ports:
      - 0.0.0.0:8085:8085
    container_name: mc-job-app
volumes:
  mc-job:
